d:\nuget\nuget.exe install EnterpriseLibrary.Common -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install EnterpriseLibrary.Data -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install EnterpriseLibrary.Data.SqlCe -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install EnterpriseLibrary.ExceptionHandling -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install EnterpriseLibrary.ExceptionHandling.WCF -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install EnterpriseLibrary.Logging -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install EnterpriseLibrary.PolicyInjection -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install EnterpriseLibrary.SemanticLogging -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install EnterpriseLibrary.SemanticLogging.Database -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install EnterpriseLibrary.SemanticLogging.WindowsAzure -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install EnterpriseLibrary.TransientFaultHandling -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install EnterpriseLibrary.TransientFaultHandling.Caching -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install EnterpriseLibrary.TransientFaultHandling.Configuration -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install EnterpriseLibrary.TransientFaultHandling.Data -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install EnterpriseLibrary.TransientFaultHandling.ServiceBus -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install EnterpriseLibrary.TransientFaultHandling.WindowsAzure.Storage -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install EnterpriseLibrary.Validation -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install EnterpriseLibrary.Validation.Integration.AspNet -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install EnterpriseLibrary.Validation.Integration.WCF -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install EnterpriseLibrary.Validation.Integration.WinForms -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install EnterpriseLibrary.Validation.Integration.WPF -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install EntityFramework -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Google.Apis.Tasks.v1 -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Ix-Async -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Ix-Main -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Microsoft.AspNet.Cors -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Microsoft.AspNet.Mvc -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Microsoft.AspNet.SignalR -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Microsoft.AspNet.SignalR.Client -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Microsoft.AspNet.SignalR.Owin -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Microsoft.AspNet.SignalR.SelfHost -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Microsoft.AspNet.Web.Optimization -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Microsoft.AspNet.WebApi -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Microsoft.AspNet.webapi.Cors -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Microsoft.AspNet.WebApi.Owin -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Microsoft.AspNet.WebApi.OwinSelfHost -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Microsoft.AspNet.WebApi.SelfHost -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Microsoft.AspNet.WebApi.Tracing -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Microsoft.AspNet.WebPages.OAuth -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Microsoft.Bcl -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Microsoft.Bcl.Build -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Microsoft.Bcl.Compression -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Microsoft.Bcl.Immutable -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Microsoft.Composition -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Microsoft.Data.Edm -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Microsoft.Data.OData -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Microsoft.Hadoop.Client -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Microsoft.IdentityModel -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Microsoft.IdentityModel.Clients.ActiveDirectory -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Microsoft.Net.Http -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Microsoft.Owin -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Microsoft.Owin.Cors -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Microsoft.Owin.Diagnostics -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Microsoft.Owin.Host.HttpListener -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Microsoft.Owin.Host.SystemWeb -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Microsoft.Owin.Security -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Microsoft.Owin.Security.Cookies -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Microsoft.Owin.Security.Google -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Microsoft.Owin.Security.Jwt -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Microsoft.Owin.Security.MicrosoftAccount -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Microsoft.Owin.Security.OAuth -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Microsoft.Owin.SelfHost -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Microsoft.Owin.StaticFiles -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Microsoft.Owin.Testing -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Microsoft.Tpl.Dataflow -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Newtonsoft.Json -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install OwinHost -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Prism -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Prism.MEFExtensions -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Prism.Phone -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Prism.PubSubEvents -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Prism.StoreApps -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Prism.UnityExtensions -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Rx_Experimental-Xaml -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Rx-Core -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Rx-Experimental -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Rx-Interfaces -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Rx-Linq -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Rx-Main -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Rx-PlatformServices -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Rx-Providers -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Rx-Remoting -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Rx-Silverlight -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Rx-Testing -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Rx-WindowStoreApps -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Rx-WinForms -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Rx-WinRT -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Rx-WPF -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Rx-Xaml -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install System.IdentityModel.Tokens.Jwt -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install System.IdentityModel.Tokens.ValidatingIssuerNameRegistry -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Unity -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
d:\nuget\nuget.exe install Unity.Interception -NoCache -Verbosity detailed -OutputDirectory D:\Microshaoft.Nuget.Packages\
rem -ConfigFile D:\Microshaoft.Nuget.Packages\%1.packages.config
